version: "3.7"

services:
  scylla-manager:
    image: scylladb/scylla-manager:2.6.3
    networks:
      public:
    depends_on:
      - scylla-manager-db

  scylla-manager-db:
    image: scylladb/scylla:4.6.3
    networks:
      public:
    command: --smp 1

  scylla:
    build:
      context: .
    image: scylladb/scylla-with-agent:4.6.3
    networks:
      public:
        ipv4_address: 192.168.100.100
    command: --smp 1

  minio:
    image: minio/minio:latest
    networks:
      public:
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

networks:
  public:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24